From alpine:3.17

Run apk add R-dev \
    R \
    pandoc \
    bash \
    linux-headers \
    build-base \
    freetype \
    libxml2 \
    libxml2-dev \
    geos-dev \
    gdal-dev \
    proj-dev \
    wget \
    ca-certificates \
    expat-dev

Run apk add font-inconsolata font-dejavu font-noto font-noto-cjk font-awesome font-noto-extra

Run wget https://downloads.unidata.ucar.edu/udunits/2.2.28/udunits-2.2.28.tar.gz --no-check-certificate

Run tar -xvf udunits-2.2.28.tar.gz
Run cd udunits-2.2.28 && ./configure --prefix=/usr/local && make && make install

ENV OSFONTDIR=/usr/share/fonts
RUN fc-cache --really-force --verbose

Run Rscript -e 'install.packages(c("codetools","pheatmap","rmarkdown","timeseries","tidyr","dplyr"),repos="http://cran.r-project.org", Ncpus=8)'
# It seems like ggplot2 needs to be installed separately
Run Rscript -e 'install.packages("ggplot2",repos="http://cran.r-project.org", Ncpus=8)'
