name: "mageck_count"
description: mageck count for functional genomics, reads are usually mapped to a specific sgRNA
keywords:
  - sort
  - functional genomics
  - sgRNA
  - CRISPR-Cas9
tools:
  - "mageck":
      description: "MAGeCK (Model-based Analysis of Genome-wide CRISPR-Cas9 Knockout), an algorithm to process, QC, analyze and visualize CRISPR screening data."
      homepage: "https://sourceforge.net/p/mageck/wiki/Home/"
      documentation: "https://sourceforge.net/p/mageck/wiki/demo/#step-4-run-the-mageck-count-command"
      doi: "10.1186/s13059-014-0554-4"
      licence: "['BSD License']"

input:
  - fastqfolder:
      type: file
      description: folder containing the fastq files to analyze
  - sample_label:
      type: string
      description: comma-separated label associate to each fastq file and its replicates
  - fastqlist:
      type: string
      description: space-separated list of fastq files. Replicates should be included in a comma-separated string.
  - library:
      type: file
      description: library file containing the sgRNA and gene name
      pattern: "*.{csv,txt,tsv}"
  - prefix:
      type: string
      description: prefix string to be added to the output files
  - mageck_count_options:
      type: string
      description: Optional. Additional arguments to be added to the execution of the mageck count command.
      pattern: '--option "value"'

output:
  - summary:
      type: file
      description: Count summary and QC measurements.
      pattern: "*.countsummary.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - norm:
      type: file
      description: File containing normalized read counts
      pattern: "*.count_normalized.txt"
  - count:
      type: file
      description: File containing read counts
      pattern: "*.countsummary.txt"
  - report:
      type: file
      description: R markdown report files.
      pattern: "*.count_report.Rmd"
  - mageck_count.log:
      type: file
      description: Console output generated by the command

authors:
  - "@jribeiro-pfe"
